### ISSUE TITLE
Cannot parse range sets

### ISSUE THREAD

**Issue by m7stock** [alpinweis/cronex#1]
The following cron times cannot be parsed although they are valid.

```
20 8,15 * * 0-1,3-6
0 7 * * 0-3,5-6
55,25 2-21,23 * * 0,1,3,5,6
55,25 2-7,10-21,23 * * 2,4
```

**Comment by rogerhelliwell** [comment]
Confirmed that day ranges are not supported. ie:

`0 7 * * 1-4,6,7`
