### ISSUE TITLE
tzinfo update

### ISSUE THREAD

**Issue by skcc321** [alpinweis/cronex#12]
Hi there looks like "cronex" has dependency on tzinfo version which blocks update of it.

```bash
Bundler could not find compatible versions for gem "tzinfo":
  In Gemfile:
    tzinfo (~> 2.0.0)

    cronex was resolved to 0.9.0, which depends on
      tzinfo (~> 1.2.5)

```
could you please make changes in gemspec to support the newest version of tzinfo? Thank you

**Comment by alpinweis** [comment]
as a quick workaround, you pin the version of tzinfo in your app?

**Comment by alpinweis** [comment]
updated tzinfo dependency in https://github.com/alpinweis/cronex/commit/1de94ecc8f66f54c5703fe657b3f572e5481a319
