### ISSUE TITLE
Suggestion: Move locale and timezone into options

### ISSUE THREAD

**Issue by DannyBen** [alpinweis/cronex#17]
It would be nicer if all options - including locale and timezone - are treated the same.

The fact that there is an empty hash in the below call, is not very "ruby":

```ruby
Cronex::ExpressionDescriptor.new('* * * * *", {}, "fr").description
```

The problem is even more evident when you want to only set timezone

```ruby
Cronex::ExpressionDescriptor.new('* * * * *", {}, nil, "New York").description
```

Would be clearer and nicer (and dare I say idiomatic....) to do:

```ruby
Cronex::ExpressionDescriptor.new('* * * * *", locale: 'fr', timezone: "New York").description
```

**Comment by alpinweis** [comment]
👍

**Comment by alpinweis** [comment]
#18 is addressing this issue
