### ISSUE TITLE
Wrong parse for days jump

### ISSUE THREAD

**Issue by jonnynux** [alpinweis/cronex#21]
When trying to parse this kind of rule:
`30 7 1-31/2 * *` 
i get:
`Alle(ai) 7:30 AM, ogni 2 giorni, , tra il giorno 1 e il 31 del mese`

So there are two consecutive commas. I tried to figure out on myself but I got lost in the code.

**Comment by alpinweis** [comment]
fixed by PRs: #23 #24 
Thanks @jonnynux
